/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

//! Error exception handler logic.
//!
//! Error exceptions are generated by the hardware for various
//! fault conditions (bus errors, privilege violations, etc.).
//! The cause code in SSR indicates the specific error type.

use minivm_types::vm::{DEBUG_GEVB_OFFSET, ERROR_GEVB_OFFSET};

/// Error cause codes from SSR.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum ErrorCause {
    /// Bus error (precise).
    BusErrorPrecise = 0x01,
    /// Multiple-write or read-write conflict.
    MultipleRW = 0x12,
    /// Permission violation (execute).
    PermExec = 0x14,
    /// Permission violation (read).
    PermRead = 0x15,
    /// Permission violation (write).
    PermWrite = 0x16,
    /// Misaligned load.
    MisalignLoad = 0x20,
    /// Misaligned store.
    MisalignStore = 0x21,
    /// Invalid packet.
    InvalidPacket = 0x25,
    /// No guest permission (trap1 not allowed).
    NoGuestPerm = 0x1B,
}

/// Classify an error cause into an event type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ErrorAction {
    /// Deliver as error event to the guest via ERROR GEVB.
    GuestError,
    /// Deliver as debug event to the guest via DEBUG GEVB.
    GuestDebug,
    /// Fatal error: no guest to deliver to (kernel fault).
    Fatal,
}

/// Determine how to handle an error exception.
///
/// `cause`: the SSR cause code.
/// `has_gevb`: whether the current thread has a guest event vector base.
/// `is_guest_context`: whether the error occurred in guest context.
pub fn classify_error(cause: u8, has_gevb: bool, is_guest_context: bool) -> ErrorAction {
    if !has_gevb {
        return ErrorAction::Fatal;
    }

    // Debug causes get routed to the DEBUG vector
    if cause == 0x1C {
        return ErrorAction::GuestDebug;
    }

    if is_guest_context {
        ErrorAction::GuestError
    } else {
        // Error in monitor mode with a GEVB set is still delivered
        // to the guest as an error (the guest owns the faulting context)
        ErrorAction::GuestError
    }
}

/// Get the GEVB offset for an error action.
pub const fn gevb_offset_for(action: ErrorAction) -> u32 {
    match action {
        ErrorAction::GuestError | ErrorAction::Fatal => ERROR_GEVB_OFFSET,
        ErrorAction::GuestDebug => DEBUG_GEVB_OFFSET,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_classify_no_gevb() {
        assert_eq!(classify_error(0x01, false, true), ErrorAction::Fatal);
        assert_eq!(classify_error(0x14, false, false), ErrorAction::Fatal);
    }

    #[test]
    fn test_classify_debug() {
        assert_eq!(classify_error(0x1C, true, true), ErrorAction::GuestDebug);
        assert_eq!(classify_error(0x1C, true, false), ErrorAction::GuestDebug);
    }

    #[test]
    fn test_classify_guest_error() {
        assert_eq!(classify_error(0x01, true, true), ErrorAction::GuestError);
        assert_eq!(classify_error(0x14, true, true), ErrorAction::GuestError);
        assert_eq!(classify_error(0x1B, true, true), ErrorAction::GuestError);
    }

    #[test]
    fn test_classify_monitor_error() {
        assert_eq!(classify_error(0x01, true, false), ErrorAction::GuestError);
    }

    #[test]
    fn test_gevb_offsets() {
        assert_eq!(gevb_offset_for(ErrorAction::GuestError), ERROR_GEVB_OFFSET);
        assert_eq!(gevb_offset_for(ErrorAction::GuestDebug), DEBUG_GEVB_OFFSET);
        assert_eq!(gevb_offset_for(ErrorAction::Fatal), ERROR_GEVB_OFFSET);
    }
}
