name: MiniVM test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
            sudo apt update
            sudo apt install make gcc qemu wget
            sudo apt build-dep -yy qemu
      - name: Set PATH
        run: echo "PATH=${PATH}:/usr/local/bin:/opt/clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl/x86_64-linux-gnu/bin" >> ${GITHUB_ENV}
      - name: Download, Unpack Toolchain
        env:
          URL: https://artifacts.codelinaro.org/artifactory/codelinaro-toolchain-for-hexagon/19.1.2/clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl.tar.xz
        run: |
            cd /tmp
            wget --quiet ${URL}
            cd /opt
            tar xf /tmp/clang+llvm-19.1.2-cross-hexagon-unknown-linux-musl.tar.xz
      - name: build
        run: make minivm CC=hexagon-unknown-none-elf-clang
